name: setup-node
description: Setup Node.js with Volta
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        submodule: 'true'
    - name: Get node version from Volta
      id: get-node-version
      uses: keita-hino/get-node-version-from-volta@main
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
        cache: yarn
