minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # Renovate security update: next@16.1.7 || 16.2.3 || 16.2.6 || 16.2.11
  - next@16.1.7 || 16.2.3 || 16.2.6 || 16.2.11

overrides:
  minimatch: ^10.2.5

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
