export const BACKEND_API_URL = process.env.NEXT_PUBLIC_BACKEND_API_URL;
export const MS_APP_CLIENT_ID = process.env.NEXT_PUBLIC_MS_APP_CLIENT_ID;
export const MS_APP_REDIRECT_URL = process.env.NEXT_PUBLIC_MS_APP_REDIRECT_URL;
