import { execFileSync } from 'child_process';
import fs from 'fs';

const OUT_DIR = 'src/generated/api';
const SDK_FILE = `${OUT_DIR}/sdk.gen.ts`;
const GET_OPERATIONS_FILE = `${OUT_DIR}/get-operations.gen.ts`;

// OpenAPI からクライアント・型・SDK を生成する (入力 URL などの設定は openapi-ts.config.ts)
console.log(`Generating API client into ${OUT_DIR}`);

execFileSync('pnpm', ['openapi-ts'], { stdio: 'inherit' });

// SWR の useApiQuery はパス文字列をキーに GET するため、
// 「GET のパス → パラメータとレスポンスの型」の対応表を SDK から作る。
// hey-api の型には HTTP メソッドが含まれないため、SDK の関数定義から拾う。
const sdk = fs.readFileSync(SDK_FILE, 'utf8');
const getOperations = Array.from(
  sdk.matchAll(
    /\.get<(\w+)Responses, \w+, ThrowOnError>\(\{[\s\S]*?url: '([^']+)'/g
  ),
  ([, name, url]) => ({ name, url })
);

if (getOperations.length === 0) {
  throw new Error(`no GET operations found in ${SDK_FILE}`);
}

const typeNames = getOperations
  .flatMap(({ name }) => [`${name}Data`, `${name}Responses`])
  .sort();
const entries = getOperations
  .map(
    ({ name, url }) =>
      `  '${url}': {\n    data: ${name}Data;\n    response: SuccessResponse<${name}Responses>;\n  };`
  )
  .join('\n');

fs.writeFileSync(
  GET_OPERATIONS_FILE,
  `// This file is auto-generated by scripts/codegen.ts

import type { ${typeNames.join(', ')} } from './types.gen';

type SuccessResponse<T> = T extends { 200: infer R } ? R : never;

export type GetOperations = {
${entries}
};
`
);

// client/ と core/ は hey-api が同梱する fetch クライアントの実装 (型ではなくランタイム)。
// このリポジトリの tsconfig (@tsconfig/strictest の exactOptionalPropertyTypes、target es5) を
// 前提にしていないため型検査から外す。API の型 (types.gen.ts / sdk.gen.ts) は検査対象のまま
const runtimeFiles = ['client', 'core'].flatMap((dir) =>
  fs
    .readdirSync(`${OUT_DIR}/${dir}`)
    .filter((file) => file.endsWith('.ts'))
    .map((file) => `${OUT_DIR}/${dir}/${file}`)
);
for (const file of runtimeFiles) {
  const content = fs.readFileSync(file, 'utf8');
  if (!content.startsWith('// @ts-nocheck')) {
    fs.writeFileSync(file, `// @ts-nocheck\n${content}`);
  }
}

console.log(`codegen complete (${getOperations.length} GET operations)`);
