name: E2E

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    name: E2E test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DEBUG_MODE: 'false'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Cache Playwright browsers
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: E2E test
        run: pnpm run test:e2e
